### ISSUE TITLE
could not convert AIF-C compress files

### ISSUE THREAD

**Issue by fmdallas** [jiaaro/pydub#102]
>>> from pydub import AudioSegment
>>> aac_version = AudioSegment.from_file("hello.aiff", "wav")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pydub/audio_segment.py", line 345, in from_file
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1
>>> aac_version = AudioSegment.from_file("hello.aiff", "wma")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pydub/audio_segment.py", line 345, in from_file
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

**Comment by jiaaro** [comment]
I believe the correct format is `aiff` (like `AudioSegment.from_file("hello.aiff", "aiff")`)

**Comment by jiaaro** [comment]
Opened a new issue #105 – which is related to this/would have been useful in this case

**Comment by jiaaro** [comment]
Ok it's been over a month, closing :smile: 

as always, reopen if I've made a mistake
