### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by anmaz** [jiaaro/pydub#209]
i want use playback  to play a music

but it alway tell me that i don't have permission,by the way, i can use cmd.exe  to play a music.

code like that:
In [9]: sou1=AudioSegment.from_mp3(r'd:\02.mp3')

In [10]: play(sou1)
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-11-dd72200cff50> in <module>()
----> 1 play(sou1)

c:\python27\lib\site-packages\pydub\playback.pyc in play(audio_segment)
     44         _play_with_pyaudio(audio_segment)
     45     except ImportError:
---> 46         _play_with_ffplay(audio_segment)

c:\python27\lib\site-packages\pydub\playback.pyc in _play_with_ffplay(seg)
     16 def _play_with_ffplay(seg):
     17     with NamedTemporaryFile("w+b", suffix=".wav") as f:
---> 18         seg.export(f.name, "wav")
     19         subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner",
 f.name])
     20

c:\python27\lib\site-packages\pydub\audio_segment.pyc in export(self, out_f, for
mat, codec, bitrate, parameters, tags, id3v2_version, cover)
    579         id3v2_allowed_versions = ['3', '4']
    580
--> 581         out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
    582         out_f.seek(0)
    583

c:\python27\lib\site-packages\pydub\utils.pyc in _fd_or_path_or_tempfile(fd, mod
e, tempfile)
     57
     58     if isinstance(fd, basestring):
---> 59         fd = open(fd, mode=mode)
     60
     61     return fd

IOError: [Errno 13] Permission denied: 'c:\\users\\admini~1\\appdata\\local\\tem
p\\tmpuzjjby.wav'

### System configuration
- Python version: 2.7
- Pydub version: 0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 3.3.3

**Comment by jiaaro** [comment]
Pydub uses [temp files, specifically NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html) pretty heavily. It looks like you don't have permission to write in the temp directory your python interpreter is configured to use.

You can try setting the `TMPDIR` environment variable which is [used by python to determine where to store temporary files (by default)](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)

**Comment by pdsing** [comment]
I changed the TMPDIR environment variable to a subfolder of the current directory. It is still giving the same error. My python program is able to write and read files from this folder for sure. Somehow pydub seems to throw the error:

> Traceback (most recent call last):
  File "try_pydub.py", line 115, in <module>
    sys.exit(main())
  File "try_pydub.py", line 110, in main
    create_90_secs_audio(full_path_wav_file, full_path_audio_segments)
  File "try_pydub.py", line 51, in create_90_secs_audio
    play(sound)
  File "C:\Python27\lib\site-packages\pydub\playback.py", line 46, in play
    _play_with_ffplay(audio_segment)
  File "C:\Python27\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\Python27\lib\site-packages\pydub\audio_segment.py", line 581, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Python27\lib\site-packages\pydub\utils.py", line 59, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
IOError: [Errno 13] Permission denied: 'c:\\users\\pd\\ml\\ebook-v2\\tmp\\tmpn2yvsv.wav'

**Comment by kkealy** [comment]
Seriously, you **still** haven't figured this out?
This issue has been open for 9 months, jesus.

Lemme explain it to you, in a way that you can understand.

So, you open this temp file using 'with', right?
```python
def _play_with_ffplay(seg):
    with NamedTemporaryFile("w+b", suffix=".wav") as f:
        seg.export(f.name, "wav")
        subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])
```

But then you pass its name to AudioSegment.export(), which is, as you described, formatted as string:
```python
out_f (string):
```

At this point, the file still open. Then you open it again:
```python
out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
```

On linux distros, it works, but Windows isn't as forgiving. Opening a file twice, what for?
So, when you try to open it again, Windows tells you to gtfo because it's already opened.
The more you know.

A quick and dirty fix is to just save the name in a local variable, and pass that to the seg.export and subprocess.call calls, like this:

```python
def _play_with_ffplay(seg):
    with NamedTemporaryFile("w+b", suffix=".wav") as f:
        fileName = f.name

    seg.export(fileName, "wav")
    subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", fileName])
    os.remove(fileName)
```

But at the end of the day, antlarr's solution is better. No need to write pointless shite to the disk for every single audio playback.

Goodest & bestest regards,
Me, yeah.

**Comment by jsl303** [comment]
Any update on this? I also have the problem.
I'm running Windows 10, and I installed the master branch.
The error message is below.
Thanks,

Traceback (most recent call last):                                                                                      
  File "<stdin>", line 1, in <module>                                                                                   
  File "C:\Users\jl\Anaconda3\envs\audionews\lib\site-packages\pydub\playback.py", line 71, in play                  
    _play_with_ffplay(audio_segment)                                                                                    
  File "C:\Users\jl\Anaconda3\envs\audionews\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay     
    seg.export(f.name, "wav")                                                                                           
  File "C:\Users\jl\Anaconda3\envs\audionews\lib\site-packages\pydub\audio_segment.py", line 780, in export          
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')                                                                       
  File "C:\Users\jl\Anaconda3\envs\audionews\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile  
    fd = open(fd, mode=mode)                                                                                            
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jl\\AppData\\Local\\Temp\\tmp5aed_m3d.wav'

**Comment by liangzid** [comment]
Have Someone solved this problem? Please help me.
```
Traceback (most recent call last):
  File "D:/desktop/MIDI_learning/test.py", line 26, in <module>
    play(song_PianDuan_s[i])
  File "D:\games\Anaconda\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "D:\games\Anaconda\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "D:\games\Anaconda\lib\site-packages\pydub\audio_segment.py", line 780, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "D:\games\Anaconda\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\22730\\AppData\\Local\\Temp\\tmpj5yymayl.wav'

```

**Comment by dimitri320** [comment]
Same here, and looks like still no solution. I'm working on a Mac

**Comment by zegevlier** [comment]
I have the same problem. I'm on windows 10.

**Comment by pholpar** [comment]
I had a similar problem (the same kind of "PermissionError: [Errno 13] Permission denied") with playback, and installing simpleaudio (executing 'pip install simpleaudio') solved the issue.
A comment regarding playback from page https://github.com/jiaaro/pydub#installation: "simpleaudio strongly recommended, even if you are installing ffmpeg/libav"
See this issue: https://github.com/jiaaro/pydub/issues/343

**Comment by NianhengWu** [comment]
On win 10, installing `simpleaudio` also can solve the problem.

**Comment by majorwitty** [comment]
On Win 10 64-bit installing simpleaudio did not fix problem.

**Comment by GillHawk** [comment]
The fix for windows and other OSs that do not support opening same file twice is close the file stream before open it again. As pointed out by "kkealy", file is first opened by NamedTemporaryFile() then by seg.export() .

Added a line in playback.py:

```
def _play_with_ffplay(seg):
    with NamedTemporaryFile("w+b", suffix=".wav") as f:
        **f.close() # close the file stream**
        seg.export(f.name, "wav")
        subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])
```

**Comment by peterhudson** [comment]
I used @GillHawk solution... worked like a charm on Win10.

**Comment by zaphodikus** [comment]
How is this one-liner bug fix not published before closing this ticket?

**Comment by fmaillar** [comment]
> The fix for windows and other OSs that do not support opening same file twice is close the file stream before open it again. As pointed out by "kkealy", file is first opened by NamedTemporaryFile() then by seg.export() .
> 
> Added a line in playback.py:
> 
> ```
> def _play_with_ffplay(seg):
>     with NamedTemporaryFile("w+b", suffix=".wav") as f:
>         f.close() # close the file stream
>         seg.export(f.name, "wav")
>         subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])
> ```

That's it. This line resolve the problem :)

**Comment by aminzakizebarjad** [comment]
as mentioned [here](https://stackoverflow.com/a/58955530/15203736) there is always with tempfile so i recommand change the playback.py to this :   
`
import subprocess
from tempfile import NamedTemporaryFile
from .utils import get_player_name, make_chunks
import random
import os
import tempfile


class CustomNamedTemporaryFile:
    """
    This custom implementation is needed because of the following limitation of tempfile.NamedTemporaryFile:

    > Whether the name can be used to open the file a second time, while the named temporary file is still open,
    > varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).
    """
    def __init__(self, mode='wb', delete=True, suffix = ''):
        self._mode = mode
        self._delete = delete
        self.suffix = suffix

    def __enter__(self):
        # Generate a random temporary file name
        file_name = os.path.join(tempfile.gettempdir(), os.urandom(24).hex())
        # Ensure the file is created
        open(file_name+self.suffix, "x").close()
        # Open the file in the given mode
        self._tempFile = open(file_name+self.suffix, self._mode)
        return self._tempFile

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._tempFile.close()
        if self._delete:
            os.remove(self._tempFile.name)
            
def _play_with_ffplay(seg):
    PLAYER = get_player_name()
    # with NamedTemporaryFile("w+b", suffix=".wav") as f:
    with CustomNamedTemporaryFile(mode='wb', suffix = ".wav") as f:
        seg.export(f.name, "wav")
        subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])

`

**Comment by khadimFaye** [comment]
im working on windows 11 pro but same problem do anyone have solution??

**Comment by DaslavCl** [comment]
> im working on windows 11 pro but same problem do anyone have solution??

just "pip install simpleaudio"
magic fix for windows11

**Comment by liam-keepmove** [comment]
> The fix for windows and other OSs that do not support opening same file twice is close the file stream before open it again. As pointed out by "kkealy", file is first opened by NamedTemporaryFile() then by seg.export() .
> 
> Added a line in playback.py:
> 
> ```
> def _play_with_ffplay(seg):
>     with NamedTemporaryFile("w+b", suffix=".wav") as f:
>         f.close() # close the file stream
>         seg.export(f.name, "wav")
>         subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])
> ```

yes! this method is useful.

**Comment by pintert3** [comment]
Is there a problem with fixing this issue? It looks like it's been on hold for a VERY LONG time, given that it's basically a one liner.

**Comment by zdyy001** [comment]
> The fix for windows and other OSs that do not support opening same file twice is close the file stream before open it again. As pointed out by "kkealy", file is first opened by NamedTemporaryFile() then by seg.export() .
> 
> Added a line in playback.py:
> 
> ```
> def _play_with_ffplay(seg):
>     with NamedTemporaryFile("w+b", suffix=".wav") as f:
>         f.close() # close the file stream
>         seg.export(f.name, "wav")
>         subprocess.call([PLAYER, "-nodisp", "-autoexit", "-hide_banner", f.name])
> ```

It does work!

**Comment by niloriver** [comment]
as @DaslavCl  already said "pip install simpleaudio" magically solves the problem on Windows 11.
