### ISSUE TITLE
How to convert 4 channel wav file to mono?

### ISSUE THREAD

**Issue by Ishvn** [jiaaro/pydub#246]
Here is my code, I'm trying to convert a 4 channel stereo wav file to mono. I initially got an error saying fn
```
from os import path

from pydub import AudioSegment
from pydub import pyaudioop

file_name = AudioSegment.from_file(path.join(
    path.dirname(__file__),
    'test2.wav'), format = "wav")

file_name = file_name.set_channels(1)

file_name.export(path.join(path.dirname(
            path.realpath(__file__)), "test2.wav"), format="wav")
```
Initially i got this error:
```
/usr/local/lib/python2.7/dist-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/home/ishan/Google_Cloudspeech_on_pepper/cloudspeechtest.py", line 21, in <module>
    file_name = file_name.set_channels(1)
  File "/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.py", line 745, in set_channels
    converted = fn(self._data, self.sample_width, 1, 1)
UnboundLocalError: local variable 'fn' referenced before assignment
```
So I edited the line where the error came from in the audio_segment pydub document and added an extra 'elif' to support 4 channel files:
```
def set_channels(self, channels):
        if channels == self.channels:
            return self

        if channels == 2 and self.channels == 1:
            fn = audioop.tostereo
            frame_width = self.frame_width * 2
        elif channels == 1 and self.channels == 2:
            fn = audioop.tomono
            frame_width = self.frame_width // 2
        #added below elif
        elif channels == 1 and self.channels == 4:
            fn = audioop.tomono
            frame_width = self.frame_width // 2

        converted = fn(self._data, self.sample_width, 1, 1)

        return self._spawn(data=converted,
                           overrides={
                               'channels': channels,
                               'frame_width': frame_width})
```
It successfully converts the file to mono but the audio is heavily slowed down and distorted. I know it's not the correct way to convert this anyway so does anyone know to do it? 
I tried attaching my 4 channel wav test file but it wouldn't work

- Python version: 2.7
- Pydub version: 0.20.0
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: latest

**Comment by jiaaro** [comment]
frame width would need to be divided by 4 since each frame how has a data for only one channel (instead of 4)

**Comment by madhubhargav** [comment]
I am still seeing this issue in 0.23.1. Is this fix shipped?

**Comment by jfuruness** [comment]
I get this:
      <class 'UnboundLocalError'>: local variable 'fn' referenced before assignment
When using it on this song: https://www.youtube.com/watch?v=7R9eHA6YiP8
