### ISSUE TITLE
Error Manipulating Big (1Gb) MP3 File

### ISSUE THREAD

**Issue by facdo** [jiaaro/pydub#294]
I am trying to split a 12 hour mp3 audio file into 103 tracks. Basically, I am following the instructions to open, split and export a mp3 file, using something like:

`pydub.AudioSegment.from_mp3(audio_file_name)[start:finish].export(new_track, format='mp3')`

When I test with a small mp3 file it works just fine, but when I try to load the 1Gb file it crashes with the following error after about 30min running:

_Traceback (most recent call last):
  File "c:\Users\20006083\Downloads\YoutubeMusic\split_audio.py", line 61, in <module>
    song = AS.from_mp3(audio_file)
  File "C:\Users\40000438\AppData\Local\Continuum\Anaconda3\lib\site-packages\pydub\audio_segment.py", line 707, in from_mp3
    return cls.from_file(file, 'mp3', parameters)
  File "C:\Users\40000438\AppData\Local\Continuum\Anaconda3\lib\site-packages\pydub\audio_segment.py", line 698, in from_file
    fix_wav_headers(p_out)
  File "C:\Users\40000438\AppData\Local\Continuum\Anaconda3\lib\site-packages\pydub\audio_segment.py", line 141, in fix_wav_headers
    data[4:8] = struct.pack('<I', len(data) - 8)
struct.error: argument out of range_

I was monitoring the memory usage while running my code, It got quite high, almost to the full 16Gb or RAM availiable in my computer. I am not sure if this is an issue with the library or it might be a crash related to memory overflow. Either way, I thought it would be nice to open this thread so the developers can verify this.

I am using python 3.6.1, the latest version of pydub (I installed today using the pip command) and also the latest version of ffmpeg (I got this file: ffmpeg-20180619-a990184-win64-shared). The audio file I am using is the audio from this youtube link:

https://www.youtube.com/watch?v=F__LuHDJko0&t=11595s

Any help solving this issue would be much appreciated.

**Comment by jiaaro** [comment]
pydub loads the raw audio samples into memory for each audio file you open. In the case of a 1GB mp3 file, that could easily be more than 16 GB of RAM. I'm pretty sure the crash you eventually hit _was_ due to running out of available memory

**Comment by facdo** [comment]
Humm, that might be the issue. I will try running my code on a 32Gb computer.

**Comment by arogozhnikov** [comment]
@jiaaro 
I'm having the same issue, but my ram is pretty large, and audio is not that huge. 
However I'm facing the following:

```
errorTraceback (most recent call last)
<ipython-input-158-6ca5d033baf1> in <module>()
      3 sounds = [AudioSegment.from_mp3(name) for name in files]
      4 
----> 5 sum(sounds).export("/data/speech/kireev/concatenated.mp3", format="mp3")

/usr/local/lib/python3.6/dist-packages/pydub/audio_segment.py in export(self, out_f, format, codec, bitrate, parameters, tags, id3v2_version, cover)
    790         # a float in python 2 doesn't throw an exception
    791         wave_data.setnframes(int(self.frame_count()))
--> 792         wave_data.writeframesraw(self._data)
    793         wave_data.close()
    794 

/usr/lib/python3.6/wave.py in writeframesraw(self, data)
    414         if not isinstance(data, (bytes, bytearray)):
    415             data = memoryview(data).cast('B')
--> 416         self._ensure_header_written(len(data))
    417         nframes = len(data) // (self._sampwidth * self._nchannels)
    418         if self._convert:

/usr/lib/python3.6/wave.py in _ensure_header_written(self, datasize)
    455             if not self._framerate:
    456                 raise Error('sampling rate not specified')
--> 457             self._write_header(datasize)
    458 
    459     def _write_header(self, initlength):

/usr/lib/python3.6/wave.py in _write_header(self, initlength)
    472             self._nchannels * self._framerate * self._sampwidth,
    473             self._nchannels * self._sampwidth,
--> 474             self._sampwidth * 8, b'data'))
    475         if self._form_length_pos is not None:
    476             self._data_length_pos = self._file.tell()

error: 'L' format requires 0 <= number <= 4294967295
```

Which indicates that L in struct is just too small.

**Comment by arogozhnikov** [comment]
Hmm. The is of total length 16 hours. This suggests that there is either a bug, or conversion is terrible inefficient
`16 * 3600 * 40000 << 4294967295

**Comment by kmahelona** [comment]
Is it possible for pydub to support file streaming? Rather than loading a whole file into memory, just load it's information and provide an iterator in case you need to process the audio bits.

**Comment by thomasaarholt** [comment]
I'm running into @arogozhnikov's problem as well. I was concatenating a series of audio files in the same manner, albeit I joined them by reading them one by one to avoid taking up twice the memory (a "total" file in addition to the individual files). 

My python instance is currently at 8GB, which is probably the size of the file being written.

**Comment by JPery** [comment]
With pull request #345 you could open little AudioSegments so you don't have to load the entire audio file into memory

**Comment by derek-adair** [comment]
+1 for JPery's PR, but it seems like file streaming would be an obvious win as well.

@kmahelona  - perhaps you could share your progress so far?

**Comment by kmahelona** [comment]
My workaround works - https://github.com/TeHikuMedia/wahi-korero/blob/master/wahi_korero/audiosegment.py - and we’re using it in “production.”

It’s more of a quick fix and I think would take a bit of effort to update pydub. Oh and it works blazingly fast even on an hour long recording! That’s for segmenting with webrtcvad.

**Comment by jamesdeluk** [comment]
I presume this is still an problem, as I'm getting the same issue.

File length is ~33mins, file size is ~700MB, 16GB RAM on Windows 10.

Any plans for a fix or workaround?

**Comment by jamesdeluk** [comment]
Are there any other known fixes/workarounds?

I can't use @kmahelona 's solution as it doesn't have silent or len, and there are SyntaxWarnings on import - but then again, it is a quick fix from over a year ago :)

My file is ~33min, ~700MB, and I have 16GB RAM, for reference.

**Comment by JPery** [comment]
Hi, @jamesdeluk. Can you describe your problem? I think you should be able to load your audio file without any problem. The issue comes as @facdo was trying to load a 12 hour audio file (1GB in mp3 compressed format). I'm working with files about 30 to 60 minutes each at all times without problems.

**Comment by jamesdeluk** [comment]
Source code is here: https://github.com/jamesdeluk/Python-Audio-TSASM/blob/master/tsasm.ipynb

Basically, I'm converting ~140 individual audio tracks to AudioSegments, processing them, then merging them with a loop, then trying to export.

The full error is:
`error                                     Traceback (most recent call last)
<ipython-input-23-2bcc3b3829ad> in <module>
----> 1 merged.export(f'merged.mp3', format='mp3')

~\AppData\Roaming\Python\Python38\site-packages\pydub\audio_segment.py in export(self, out_f, format, codec, bitrate, parameters, tags, id3v2_version, cover)

C:\Program Files\Python38\lib\wave.py in writeframesraw(self, data)
    425         if not isinstance(data, (bytes, bytearray)):
    426             data = memoryview(data).cast('B')
--> 427         self._ensure_header_written(len(data))
    428         nframes = len(data) // (self._sampwidth * self._nchannels)
    429         if self._convert:

C:\Program Files\Python38\lib\wave.py in _ensure_header_written(self, datasize)
    466             if not self._framerate:
    467                 raise Error('sampling rate not specified')
--> 468             self._write_header(datasize)
    469 
    470     def _write_header(self, initlength):

C:\Program Files\Python38\lib\wave.py in _write_header(self, initlength)
    478         except (AttributeError, OSError):
    479             self._form_length_pos = None
--> 480         self._file.write(struct.pack('<L4s4sLHHLLHH4s',
    481             36 + self._datalength, b'WAVE', b'fmt ', 16,
    482             WAVE_FORMAT_PCM, self._nchannels, self._framerate,

error: argument out of range`

**Comment by JPery** [comment]
Hi, @jamesdeluk.

In your code you can save a lot of memory merging the audiosegments directly instead of saving them in a list first. You can do something like:

`-
merged = AudioSegment.empty()
for source_file in source_files:
    sound = AudioSegment.from_file(source_file, format="m4a")
    trimmed_sound = do_stuff(sound)
    merged += trimmed_sound
`

Hope this helps!

**Comment by jamesdeluk** [comment]
@JPery Yeah, that makes sense. I only did it my way just because I like to break things down, especially at first, and I was trying multiple different things at the same time (merging, trimming, overlaying, exporting, etc). Probably should have functionised it.

Either way, I simplified the script (no processing) and it still has the same error.

```
tracks = glob.glob(f'{source_dir}*.mp3')
merged = AudioSegment.empty()
for track in tracks:
    sound = AudioSegment.from_file(track, format="mp3")
    merged += sound
print("Merged")
merged.export(f'merged.mp3', format='mp3')
```

The merging worked (as proved by the print), but the same error during the exporting.

For reference, Python is using 5.7GB RAM. My system has 16, of which 11 (including Python) is used - so it doesn't look like I'm out.

This is a 9hr, 500MB file.

**Comment by wanghaisheng** [comment]
@jamesdeluk  how did you ifx that

**Comment by DJFT** [comment]
@JPery I have been using your temporary files function to chunk the audios in my code, and it improved the RAM usage by approximately 20% which is great. But I have been trying to work it in further into the strip_silence function, but it doesn't seem to provide any further performance boost when I do this and my code is still using extreme amounts of RAM. In addition, it appears I am at the 'limit' for chunking the audio at the top level (10 mins) as if I go down further (e.g to 5 mins) it has no further RAM impact. Was hoping you could help (and many thanks for making the function in the first place as it has helped me considerably)

`for file in audio_files:
    mimeType = file["type"]
    filename = file['filename']
    with NamedTemporaryFile(mode='wb', delete=True) as input:
        input.write(file['bytes'].getvalue())
        segment = AudioSegment.from_file_using_temporary_files(input.name)
        seg_duration = int(round(segment.duration_seconds,0))
        del segment # memory management
        pre_length_raw += seg_duration
        chunk_number = (seg_duration // chunk_size + (seg_duration % chunk_size > 0))
        for i in range(0,chunk_number):
            print(f'Chunk: {i+1}')
            # need to chunk the file and use temporary files otherwise the ram usage goes astronomical
            subsegment = AudioSegment.from_file_using_temporary_files(input.name, start_second=i*chunk_size,duration=chunk_size)
            subsegment = effects.strip_silence(subsegment, silence_len=400, silence_thresh=-40, padding=150)
            post_dictation += subsegment
            del subsegment # memory management`
