### ISSUE TITLE
CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

### ISSUE THREAD

**Issue by bluemonk482** [jiaaro/pydub#332]
I am testing some code on a VM, and all of sudden pydub starts giving error for loading wav files. Why??

```
Python 3.5.5 |Anaconda custom (64-bit)| (default, May 13 2018, 21:12:35)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pydub import AudioSegment

In [2]: file_path = "/data/SPEECH_SEGMENTS/T/Ses05M_script03_2_201.85128559266252-202.72063311702868.wav"

In [3]: audio = AudioSegment.from_wav(file_path)
---------------------------------------------------------------------------
CouldntDecodeError                        Traceback (most recent call last)
<ipython-input-3-6e8dad0eb1f1> in <module>()
----> 1 audio = AudioSegment.from_wav(file_path)

/anaconda/envs/py35/lib/python3.5/site-packages/pydub/audio_segment.py in from_wav(cls, file, parameters)
    726     @classmethod
    727     def from_wav(cls, file, parameters=None):
--> 728         return cls.from_file(file, 'wav', parameters)
    729
    730     @classmethod

/anaconda/envs/py35/lib/python3.5/site-packages/pydub/audio_segment.py in from_file(cls, file, format, codec, parameters, **kwargs)
    702             raise CouldntDecodeError(
    703                 "Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(
--> 704                     p.returncode, p_err))
    705
    706         p_out = bytearray(p_out)

CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

b'ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609\n  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv\n  WARNING: library configuration mismatch\n  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc\n  libavutil      54. 31.100 / 54. 31.100\n  libavcodec     56. 60.100 / 56. 60.100\n  libavformat    56. 40.101 / 56. 40.101\n  libavdevice    56.  4.100 / 56.  4.100\n  libavfilter     5. 40.101 /  5. 40.101\n  libavresample   2.  1.  0 /  2.  1.  0\n  libswscale      3.  1.101 /  3.  1.101\n  libswresample   1.  2.101 /  1.  2.101\n  libpostproc    53.  3.100 / 53.  3.100\n[wav @ 0x2174360] invalid start code [0][0][0][0] in RIFF header\n/data/SPEECH_SEGMENTS/T/Ses05M_script03_2_201.85128559266252-202.72063311702868.wav: Invalid data found when processing input\n'
```

### Your System configuration
- Python version: 3.5.5
- Pydub version: latest version

**Comment by ykpercy** [comment]
`from pydub import AudioSegment

sourse_path = "f:\\cs\\python\\lib\\site-packages\\librosa\\util\\example_data\\Kevin_MacLeod_-_Vibe_Ace.ogg"
destin_path = "F:\\CS\\PY_PRO\\py_music\\files\\Kevin_MacLeod_-_Vibe_Ace.wav"

sound = AudioSegment.from_ogg(sourse_path)
sound.export(destin_path , format="wav")`

and the output is following:
---------------------------------------------------------------------------
CouldntDecodeError                        Traceback (most recent call last)
<ipython-input-20-c1f65558d662> in <module>()
      4 destin_path = "F:\\CS\\PY_PRO\\py_music\\files\\Kevin_MacLeod_-_Vibe_Ace.wav"
      5 
----> 6 sound = AudioSegment.from_ogg(sourse_path)
      7 print(sound)
      8 sound.export(destin_path , format="wav")

f:\cs\python\lib\site-packages\pydub\audio_segment.py in from_ogg(cls, file, parameters)
    722     @classmethod
    723     def from_ogg(cls, file, parameters=None):
--> 724         return cls.from_file(file, 'ogg', parameters)
    725 
    726     @classmethod

f:\cs\python\lib\site-packages\pydub\audio_segment.py in from_file(cls, file, format, codec, parameters, **kwargs)
    702             raise CouldntDecodeError(
    703                 "Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(
--> 704                     p.returncode, p_err))
    705 
    706         p_out = bytearray(p_out)

CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

b'ffmpeg version N-92936-ged3b64402e Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 8.2.1 (GCC) 20181201\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt\r\n  libavutil      56. 25.100 / 56. 25.100\r\n  libavcodec     58. 43.100 / 58. 43.100\r\n  libavformat    58. 25.100 / 58. 25.100\r\n  libavdevice    58.  6.101 / 58.  6.101\r\n  libavfilter     7. 47.100 /  7. 47.100\r\n  libswscale      5.  4.100 /  5.  4.100\r\n  libswresample   3.  4.100 /  3.  4.100\r\n  libpostproc    55.  4.100 / 55.  4.100\r\n[ogg @ 0000000000623c00] cannot find sync word\r\nf:\\cs\\python\\lib\\site-packages\\librosa\\util\\example_data\\Kevin_MacLeod_-_Vibe_Ace.ogg: Invalid data found when processing input\r\n'

**Comment by prams628** [comment]
Can you try working with the function 'from_file' instead of 'from_wav'? I was facing the same error and this somehow worked for me. I really don't know how.
PS: I'm using ffmpeg version 4.1.3

**Comment by BaekSe** [comment]
thanks to @prams628 . I got same problem from the function 'from_mp3'.
using 'from_file' worked for me.

**Comment by altaf-navalur** [comment]
using 'from_file' worked for me too. Thanks

**Comment by LorianDo** [comment]
My purpose: to convert mp3 to wav
At the beginning, I used 'from_mp3' and it did work, then I changed it to 'from_file' because I wanted to convert flac to wav too, but it did not work anymore and I got the same issue. I did try to use 'from_mp3' again, but it no longer worked. Somebody please helps.

**Comment by felipeffm** [comment]
I'am with the same error. Its strange that it worked for some time and then that error started

**Comment by kurotachimi** [comment]
same as @felipeffm,
I am using 'from_file' and it worked till last week.
Python 3.6.9
pydub-0.23.1

**Comment by LorianDo** [comment]
I have just figured out where the error which happened to me, derived from. Actually, it will appear when you change the extension of a file just by renaming it, then you use the renamed file as the source and its extension as the format. The reason is that as far as I know, Pydub will only work if you use the original extension. For instance, my original file: "myfile.oext", then my renamed file: "myfile.rext". It will work if you use 'oext' in stead of 'rext'. (just in case you rename the extension of a file).

**Comment by luvensaitory** [comment]
I use from_wav() to load wave files also got this error. And I tried from_file() but didn't work.
Then I trace the code. The error was "pcm_s8 codec not supported in WAVE format" when running ffmpeg. And I finally found that, using from_file_using_temporary_files() instead. This work for me, and hope this can help you guys too!

**Comment by justinbacle** [comment]
I have the same problem here on linux when reading from Wav files. Works great on windows but not on linux.
tried from_wav, from_file and from_file_using_temporary_files but none works :s

**Comment by Tensorflow-Ranger** [comment]
I was facing the same error but when I tried reinstalling ffmpeg using `conda install -c conda-forge ffmpeg` it worked.

**Comment by LezendarySandwich** [comment]
> Can you try working with the function 'from_file' instead of 'from_wav'? I was facing the same error and this somehow worked for me. I really don't know how.
> PS: I'm using ffmpeg version 4.1.3

Thanks, I did not expect it to work but God was I wrong. You saved me.

**Comment by Lhx94As** [comment]
from_file() worked for me too.Thanks for the comment

**Comment by CarolleGoda** [comment]
Thank you! The from_file method worked for me!

**Comment by nikhil16-bhaskar** [comment]
Hi,

If you are using AudioSegment.from_wav(file_path) then correct way is AudioSegment.from_wav(file_path,'wav')
but this works best AudioSegment.from_file(file_path)

**Comment by naofumi1014** [comment]
I faced this open method error (ffmpeg==4.3.1) and solved yours comments by using "from_file" method. Thanks a lot.

**Comment by Spidy104** [comment]
Same here, it works with from_file...

**Comment by JomariHinayon** [comment]
Can somebody please help me ?
I've also encountered this kind of error.
Here's my code :

from pydub import AudioSegment
from pydub.playback import play

wav_file = AudioSegment.from_file(file="./Goo Goo Dolls  - IRIS ( LYRICS).wav", format='wav')

ERROR:

Traceback (most recent call last):
  File "C:\Users\Jomari\Desktop\Projects\Music App\tests\pydub_test.py", line 8, in <module>
    wav_file = AudioSegment.from_file(file="./Goo Goo Dolls  - IRIS ( LYRICS).wav", format='wav')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jomari\Desktop\Projects\Music App\venv\Lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 2022-12-29-git-d39b34123d-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 55.103 / 59. 55.103
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 53.100 /  8. 53.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[wav @ 000001f9a0b81100] invalid start code [0][0][0][24] in RIFF header
./Goo Goo Dolls  - IRIS ( LYRICS).wav: Invalid data found when processing input

**Comment by qaixerabbas** [comment]
I tried `AudioSegment.from_file` but that didn't work I got an answer from StackOverflow

```
try:
    audio = audiosegment.from_file(filename, "mp3")
except:
    audio = audiosegment.from_file(filename, format="mp4")
```

This worked perfectly fine. Here is the [link](https://stackoverflow.com/questions/70660431/couldntdecodeerror-decoding-failed-ffmpeg-returned-error-code-69) for complete question on StackOverflow.

**Comment by amrsharaki** [comment]
For me the issue was that I was initially converting an **mp4** to **wav**. But I was using **mp4** as my export format argument, and my export file name was **.wav**. So in my file browser everything looked fine. And when I played the audio file it played fine. But turns out ffmpeg wasn't okay with the fact that the file was saved with format argument as **mp4**. So I just re-exported my audio with format argument as **wav**. And then everything worked fine!

**Comment by udita1903** [comment]
For me none of them worked, I have 3000 audio files all of them with the extension changed to .wav
I tried to use `from_file() `and `from_file_using_temporary_files()`, but none of them work.


---------------------------------------------------------------------------
CouldntDecodeError                        Traceback (most recent call last)
Cell In[8], [line 2](vscode-notebook-cell:?execution_count=8&line=2)
      [1](vscode-notebook-cell:?execution_count=8&line=1) # sound = AudioSegment.from_file(src)
----> [2](vscode-notebook-cell:?execution_count=8&line=2) sound = AudioSegment.from_file_using_temporary_files(src)
      [3](vscode-notebook-cell:?execution_count=8&line=3) sound.export(dst, format="wav")

File [~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:624](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:624), in AudioSegment.from_file_using_temporary_files(cls, file, format, codec, parameters, start_second, duration, **kwargs)
    [622](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:622) try:
    [623](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:623)     if p.returncode != 0:
--> [624](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:624)         raise CouldntDecodeError(
    [625](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:625)             "Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(
    [626](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:626)                 p.returncode, p_err.decode(errors='ignore') ))
    [627](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:627)     obj = cls._from_safe_wav(output)
    [628](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/home/udita/audioenv/~/audioenv/lib/python3.10/site-packages/pydub/audio_segment.py:628) finally:

CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 [/](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/) 56. 70.100
  libavcodec     58.134.100 [/](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/) 58.134.100
...
  libswscale      5.  9.100 [/](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/)  5.  9.100
  libswresample   3.  9.100 [/](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/)  3.  9.100
  libpostproc    55.  9.100 [/](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/) 55.  9.100
[/tmp/tmpym2m6l98](https://vscode-remote+ssh-002dremote-002b10-002e64-002e26-002e36.vscode-resource.vscode-cdn.net/tmp/tmpym2m6l98): Invalid data found when processing input

**Comment by tailerDerdon** [comment]
Такая же проблема использовал все 3 метода не помогает виндовс 10.
