### ISSUE TITLE
Errno13 Permission denied in utils.py

### ISSUE THREAD

**Issue by mike7567** [jiaaro/pydub#343]
### Steps to reproduce
I run this simple program called puzzle.py from the command prompt as "python puzzle.py":
import pydub
import pydub.playback
r = pydub.AudioSegment.from_wav("a.wav")
pydub.playback.play(r)

I'm new to Python, so this must be a stupid error of mine, but I can't see it.

### Expected behavior
Should play the wav file. Any wav file will do here.

### Actual behavior
Tell us what happens instead:
C:\Mike\Projects>python puzzle.py
Traceback (most recent call last):
  File "puzzle.py", line 5, in <module>
    pydub.playback.play(r)
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py", line 780, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\other\\AppData\\Local\\Temp\\tmpuu4e_di6.wav'

So I inserted two Debug lines in the ...\pydub\utils.py file as below:

def _fd_or_path_or_tempfile(fd, mode='w+b', tempfile=True):
    if fd is None and tempfile:
        fd = TemporaryFile(mode=mode)

    if isinstance(fd, basestring):
        debugFD = open("\\Users\\other\\AppData\\Local\\Temp\\tmpfhzjki4u.wav", "wb+")  #debug
        print(fd, mode)                                                                                                           #debug
        fd = open(fd, mode=mode)

Which resulted in the ...\\Temp\\tmpfhzjki4u.wav being created and the followingfile the following

C:\Mike\Projects>python puzzle.py
a.wav rb
C:\Users\other\AppData\Local\Temp\tmp8lfsc8bh.wav wb+
Traceback (most recent call last):
  File "puzzle.py", line 5, in <module>
    pydub.playback.play(r)
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py", line 780, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Users\other\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\utils.py", line 59, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\other\\AppData\\Local\\Temp\\tmp8lfsc8bh.wav'

So I do have permission to create a file in the directory, but something else goes wrong

### Your System configuration
- Python version: 3.7
- Pydub version:  pydub-0.23.0.dist.info
- ffmpeg or avlib?: No
- ffmpeg/avlib version: 

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.
Any .wav file

**Comment by mike7567** [comment]
That fixed it for me too.  Thanks.

**Comment by pholpar** [comment]
@gaby64: Thanks! I have the same problem, and installing simpleaudio (executing 'pip install simpleaudio') solved the issue.
A comment regarding playback from page https://github.com/jiaaro/pydub#installation: "simpleaudio strongly recommended, even if you are installing ffmpeg/libav"

**Comment by majorwitty** [comment]
One year and one day later I find this. I installed pydub and simpleaudio only as I am only manipulating wav files with PCMU encodings.

This script:

```
from pydub.playback import play
from pydub import AudioSegment
wav_file = AudioSegment.from_wav('2019-11-22-1707_5119038_2159999999-in.wav')
play(wav_file)
```

Produces this output:

C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\utils.py:179: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "split_on_silence.py", line 19, in <module>
    play(wav_file)
  File "C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\playback.py", line 18, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\audio_segment.py", line 780, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Users\anon\Documents\python-venv\pydub\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\anon\\AppData\\Local\\Temp\\tmpt8i1kixx.wav'

**Comment by danxnader** [comment]
I have similiar issue, ffmpeg is up and running. Tried using pydub to export merged audio files in large numbers (125, to be exact), and since simpleaudio has no such functionality

**Comment by Enot890** [comment]
I have this error coming out [errno 13] permission denied audio.wav [Errno 2 No such file or directory: webcam.avi. everything worked the first time I used it. there were no errors during compilation.

**Comment by denizsincar29** [comment]
I was trying to solve this issue but pydub.play doesn't play the ogg file, however it blocks everything for the length of the file.
