### ISSUE TITLE
Error after upgrading from 0.22 -> 0.23

### ISSUE THREAD

**Issue by cmann1** [jiaaro/pydub#351]
### Actual behavior
Traceback (most recent call last):
  File "C:\localhost\sinodex\scripts\generate_waveform_json.py", line 29, in <module>
    AudioSegment.from_file(filename, filename.split('.')[-1])
  File "C:\Users\Carl\AppData\Local\Programs\Python\Python36\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Carl\AppData\Local\Programs\Python\Python36\lib\site-packages\pydub\utils.py", line 288, in mediainfo_json
    for token in extra_info[stream['index']]:
KeyError: 1

### Your System configuration
- Python version: 3.6
- Pydub version: 0.22
- ffmpeg or avlib?: avlib
- ffmpeg/avlib version: 11.7

### Is there an audio file you can include to help us reproduce?
https://1drv.ms/v/s!Aga1JaEdoW7RumexCuFjxUqPkxQU

**Comment by yunpengn** [comment]
I am facing exactly the same issue (but on Debian, using FFmpeg). Anyone can help?

**Comment by GyuminH** [comment]
I had the same issue.
I have no idea what the root problem is because I'm not familiar with python and the libraries such as rtmp and pydub. so my temporal solution is subtracting 1 from 'index' (stream['index'] -1) since (and seems that) extra_info starts with 0 but the 'index' starts with 1.
