### ISSUE TITLE
Failure to work in python3

### ISSUE THREAD

**Issue by josh-flori** [jiaaro/pydub#377]
When attempting to convert audio formats

```
from os import path
from pydub import AudioSegment

# files                                                                         
src = "/users/josh.flori/desktop/speech.mp3"
dst = "/users/josh.flori/desktop/speech.wav"

# convert wav to mp3                                                            
sound = AudioSegment.from_mp3(src)
sound.export(dst, format="wav")


```

I am met with 
```

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/users/josh.flori/desktop/test/lib/python3.6/site-packages/pydub/audio_segment.py", line 716, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/users/josh.flori/desktop/test/lib/python3.6/site-packages/pydub/audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "/users/josh.flori/desktop/test/lib/python3.6/site-packages/pydub/utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/Users/josh.flori/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Users/josh.flori/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'
```

And upon googling that error, I found that ffprobe does not work in python3, which I am using. Is that the cause of this error?

**Comment by josh-flori** [comment]
closed because I didn't follow the documentation correctly. No issue here.

**Comment by MaxPowerWasTaken** [comment]
can I ask how you resolved this @josh-flori? 

I'm getting the same error. Other issues I came across (#365, #374) are unresolved

**Comment by jiaaro** [comment]
My guess is that ffprobe is not installed – ffprobe _does_ work with python3, but depending now you install ffmpeg, you may not get other related tools like ffplay or ffprobe
