### ISSUE TITLE
Issue Importing AudioSegment

### ISSUE THREAD

**Issue by SimetriaStudio** [jiaaro/pydub#403]
### Steps to reproduce
import numpy as np
import os, sys
from pydub import AudioSegment

### Actual behavior
Getting the following error when running the file wave.py:
`Traceback (most recent call last):
  File "wave.py", line 3, in <module>
    from pydub import AudioSegment
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pydub/__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pydub/audio_segment.py", line 7, in <module>
    import wave
  File "/Users/Sim/Desktop/Audio Wave/wave.py", line 3, in <module>
    from pydub import AudioSegment
ImportError: cannot import name 'AudioSegment'
`

### Your System configuration
- Python version: 3.6.5
- Pydub version: latest (just installed it today)

**Comment by SimetriaStudio** [comment]
It didn't like the name wave.py for the file.

**Comment by Natavan-A** [comment]
Can I ask how did you resolve it?
