### ISSUE TITLE
Bug with oping a file

### ISSUE THREAD

**Issue by xkcdjerry** [jiaaro/pydub#412]
I ran this two lines:

- from pydub import AudioSegment
- AudioSegment.from_mp3(r"C:\Users\my_user_name\Desktop\cut\1.mp3")

It should have returned a AudioSegment, but it blew up!
but when I ran it using a open command, it all works out, what the heck is this??

TraceBack:
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    AudioSegment.from_mp3(r"C:\Users\58394\Desktop\cut\1.mp3")
  File "C:\Users\58394\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydub\audio_segment.py", line 716, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "C:\Users\58394\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\58394\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\58394\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\58394\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
（sorry, I am in china, it means the System cannot find the file）

- Python version: 3.7.3
- Pydub version: 0.23.1
- ffmpeg or avlib?: ffprobe
- ffmpeg/avlib version: 0.5

I put the file in the issue, here is my screenshot:
![image](https://user-images.githubusercontent.com/49294431/62859985-6b22ca00-bd31-11e9-8660-42e417720ea8.png)

**Comment by xkcdjerry** [comment]
Correction: I am using ffmpeg 1.4

**Comment by jiaaro** [comment]
That generally indicates that pydub couldn't find the ffmpeg executable. The file it couldn't find was ffmpeg. That's what the first warning was about. You can put the ffmpeg executable in your PATH, or assign the path to it to `AudioSegment.converter` - pydub looks in the working directory so it should also be possible to move ffmeg into your project root, or symlink it from there. I haven't done that myself though.

**Comment by xkcdjerry** [comment]
Thank you, and I will try to find the ffmpeg executable?But what's that second warning about ffprobe?

**Comment by jiaaro** [comment]
@xkcdjerry Basically the same thing, ffprobe (an ffmpeg tool) couldn't be found in your PATH

**Comment by xkcdjerry** [comment]
Thank you, but please can you make a easy symlink by changing the install package I can't find it, thank you! @ @jiaaro

**Comment by cainy393** [comment]
We need a way to specify the location of the prober as well as the converter and ideally some mention in the documentation about how to do this (instead of having to hunt through the bug tracker or the source code).

Setting the PATH variable is not always an option, in my case I'm creating a portable standalone app. I have seen several issues on the tracker relating to similar error messages and setting the AudioSegment.converter variable does not fix the issue. If you read the error messages they refer to utils.py:23 which is where the prober is being run, not the ffmpeg executable.
