### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Dateez** [jiaaro/pydub#467]
### Steps to reproduce
if len(os.listdir(r'C:\Users\mp95\Desktop\EMOVO\merged_mono')) == 0:
    for f in tqdm(df.fname):
        f = AudioSegment.from_wav(r'C:\Users\mp95\Desktop\EMOVO\merged\\'+f)
        f = f.set_channels(1)
        f.export(r'C:\Users\mp95\Desktop\EMOVO\merged_mono', format="wav")
### Expected behavior
Ideally i'd want to write in the merged_mono folder all the wav contained in the "merged" keeping the original name but converted from stereo to mono

### Actual behavior
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/mp95/PycharmProjects/Thesis/preproc.py", line 106, in <module>
    f.export(r'C:\Users\mp95\Desktop\EMOVO\merged_mono', format="wav")
  File "C:\Users\mp95\PycharmProjects\Thesis\venv\lib\site-packages\pydub\audio_segment.py", line 780, in export
    out_f = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Users\mp95\PycharmProjects\Thesis\venv\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mp95\\Desktop\\EMOVO\\merged_mono'

### Your System configuration
- Python version: 3.7
- Pydub version:0.23.1 
- ffmpeg or avlib?: 
- ffmpeg/avlib version: 

found this suggested solution 
Pydub uses temp files (specifically NamedTemporaryFile) pretty heavily. It looks like you don't have permission to write in the temp directory your python interpreter is configured to use.

You can try setting the TMPDIR environment variable which is used by python to determine where to store temporary files (by default)

but i have no idea on how to do it... i've tried to google it... if that could be the problem could you guys give me a more detailed procedure?

thanks everyone

**Comment by Dateez** [comment]
Didn't read carefully documentation, the code i wrote made no sense, anyways here's the update:

```
def to_mono(df):
    if len(os.listdir(r'F:\EMOVO\merged_5_mono')) == 0:
        for f in tqdm(df.fname):
            audio = AudioSegment.from_wav(r'F:\EMOVO\merged_5\\' + f)
            audio = audio.set_channels(1)
            audio.export(r'F:\EMOVO\merged_5_mono\\' + f, format="wav")
```
thanks for the library
