### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by huyvl** [jiaaro/pydub#512]
### Steps to reproduce
1.  This is my code
`	path = 'D:/VGGvox/VGGvoxtrainer/voxceleb_trainer/voxceleb/00110.m4a'
	test = AudioSegment.from_file(path, 'aac')
	##play(test)
	test.export("test.wav", format="wav")
`
2. I got this error when I ran it 

> Traceback (most recent call last):
  File "dataprep.py", line 156, in <module>
    convert(args)
  File "dataprep.py", line 118, in convert
    test = AudioSegment.from_file(path, 'aac')
  File "G:\Anaconda\lib\site-packages\pydub\audio_segment.py", line 717, in from_file
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "G:\Anaconda\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "G:\Anaconda\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "G:\Anaconda\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
>

### Expected behavior
File should converted to wav

### Actual behavior
Errors show above

### Your System configuration
- Python version: 3.5.6
- Pydub version: 0.24.1
- ffmpeg or avlib?: libav
- ffmpeg/avlib version: 11.3-win64

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.
I dont think the problem is my file, I have this this code with multiple files

**Comment by GreyAlien502** [comment]
Can you post the log output before it throws the error?
There should be a line like ```subprocess.call(...)```.

**Comment by huyvl** [comment]
> Can you post the log output before it throws the error?
> There should be a line like `subprocess.call(...)`.

Sorry, thats all I got I think
