### ISSUE TITLE
Memory leak when using AudioSegment.from_file(file = 'my_file.m4a')

### ISSUE THREAD

**Issue by fhalamos** [jiaaro/pydub#558]
I am loading a ton of .m4a files with `AudioSegment.from_file()`. After a while, I am getting [Errno 24] Too Many Open Files when running that line.

I was looking at the pydub code, and I have a feeling I know where the memory leak is, but not 100% sure.

In line 729 of audio_segment.py we have
`obj = cls._from_safe_wav(BytesIO(p_out))`

`_from_safe_wav()` will open the _io.BytesIO object, but wont close it, given that `isinstance(fd, os.PathLike)` is false (utlis.py line 65).

My code when using pydub:
```
def create_chunk_wav(audio_url, offset, duration):
    ''' 
    Create a wave chunk of a given audio.
   
    params
    audio_url: path to .m4a file
    offset, duration: integers
    '''
    sound = AudioSegment.from_file(file = audio_url)

    if offset is not None and duration is not None:
      sound = sound[offset*1000:(offset+duration)*1000]

    #Transform to .wav
    AUDIO_FILE_WAV = "transcript.wav"
    out = sound.export(AUDIO_FILE_WAV, format="wav")
    out.close()
    return AUDIO_FILE_WAV
```

### System configuration
- Python version: 3.6.9
- Pydub version: 0.24.1
- ffmpeg or avlib?: ffmpeg 
- ffmpeg/avlib version: 3.4.8

**Comment by fhalamos** [comment]
Maybe Im totally wrong and there is no need to close the _io.BytesIO object? The memory leak might be somewhere else.

**Comment by fhalamos** [comment]
Update:
Even after closing the _io.BytesIO object, I get a memory leak.

```
Traceback (most recent call last):
  File "transcript_generator.py", line 182, in create_choped_wav
    sound = AudioSegment.from_file(audio_url)
  File "/mnt/c/Users/felip/ml_for_survey_data_quality/aaa_venv/lib/python3.6/site-packages/pydub/audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/mnt/c/Users/felip/ml_for_survey_data_quality/aaa_venv/lib/python3.6/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1254, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by pcnoic** [comment]
Hey @fhalamos, did you ever find a workaround?

**Comment by fseasy** [comment]
How is going currently? I came across the same problem. I use the `memory_profile` and find a memory leak, see bellow

```
   101    844.8 MiB     15.5 MiB           1               a = AudioSegment.from_wav(path)       
   102    844.8 MiB      0.0 MiB           2               a.export(                                          
   103    844.8 MiB      0.0 MiB           1                   target_path, format=target_
path.suffix[1:]                                                                                               
   104                                                     )                                                  
   105    837.2 MiB     -7.6 MiB           1               del a                                              
   106    837.2 MiB      0.0 MiB           1               import gc                                          
   107    837.2 MiB      0.0 MiB           1               gc.collect() 
```
