### ISSUE TITLE
Unknown input format: 'wma'

### ISSUE THREAD

**Issue by henryell** [jiaaro/pydub#581]
### Steps to reproduce
code:
```
AUDIO_FILE = "./audio/book9/test1/01 Track 1.wma"
wma_version = AudioSegment.from_file(AUDIO_FILE, format="wma")
```
error log:
```
Traceback (most recent call last):
  File "d:/Project/latten/latten/main.py", line 10, in <module>
    wma_version = AudioSegment.from_file(AUDIO_FILE, format="wma")
  File "D:\Users\yh110\Anaconda3\lib\site-packages\pydub\audio_segment.py", line 775, in from_file
    p.returncode, p_err.decode(errors='ignore') ))
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

avconv version v13_dev0-1440-g34c1133, Copyright (c) 2000-2018 the Libav developers
  built on Jan  8 2018 22:33:29 with gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)
Unknown input format: 'wma'
```

### Expected behavior
Read wma file successfully.
[01 Track 1.zip](https://github.com/jiaaro/pydub/files/6291606/01.Track.1.zip)

### Actual behavior
Failed to read wma file.

### Your System configuration
- Python version: 3.7.3 64bit
- Pydub version: 0.25.1
- ffmpeg or avlib?: avlib
- ffmpeg/avlib version: libav-x86_64-w64-mingw32-20180108 (from http://builds.libav.org/windows/nightly-gpl/?C=M&O=A)

### Is there an audio file you can include to help us reproduce?
Please see the attachment.
[01 Track 1.zip](https://github.com/jiaaro/pydub/files/6291607/01.Track.1.zip)

**Comment by vanta240i** [comment]
Same issue is being experienced.

**Comment by tpcgold** [comment]
have the same issue but the strange thing: if you don't provide the format it just works with wma 🤷

**Comment by arskov** [comment]
You need to pass `format="asf"`. [ASF (Advanced Systems Format)](https://learn.microsoft.com/en-us/windows/win32/wmformat/overview-of-the-asf-format) is the Microsoft's format for all sorts of digital media streams including `wma` and `wmv`. See [ffmpeg formats](https://ffmpeg.org/ffmpeg-formats.html).

**Comment by kylefoley76** [comment]
@arskov  thanks, that did it.
