### ISSUE TITLE
Error in wave.py while trying to concatenate large MP3 file

### ISSUE THREAD

**Issue by wcarhart** [jiaaro/pydub#602]
### Steps to reproduce
I am combining a large number of MP3 files (30+) into one large file. I have attached all of the audio files to the bottom of this issue via a Google Drive link.
```
# build segments
songs = []
for link in links:
  f = save(link, folder)
  songs.append(AudioSegment.from_mp3(f))

# join files
result = reduce(lambda a, b: a + b, songs)
result.export(f'{name}.mp3', format='mp3')
```

### Expected behavior
I am expecting one large MP3 file (12hrs+) that is the concatenation of many smaller MP3 files (~20-40min each).

### Actual behavior
Sometimes this works, and sometimes it fails with following error. I could not decipher the root cause of the error from the stack trace.
```
Traceback (most recent call last):
  File "/Users/will.carhart/personal/audio/scrape.py", line 124, in <module>
    main()
  File "/Users/will.carhart/personal/audio/scrape.py", line 121, in main
    scrape(num, args.output)
  File "/Users/will.carhart/personal/audio/scrape.py", line 99, in scrape
    result.export(f'{name}.mp3', format='mp3')
  File "/Users/will.carhart/personal/audio/venv/lib/python3.9/site-packages/pydub/audio_segment.py", line 895, in export
    wave_data.writeframesraw(pcm_for_wav)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 426, in writeframesraw
    self._ensure_header_written(len(data))
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 479, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
struct.error: 'L' format requires 0 <= number <= 4294967295
Exception ignored in: <function Wave_write.__del__ at 0x10613ed30>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 326, in __del__
    self.close()
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 444, in close
    self._ensure_header_written(0)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 467, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wave.py", line 479, in _write_header
    self._file.write(struct.pack('<L4s4sLHHLLHH4s',
struct.error: 'L' format requires 0 <= number <= 4294967295
```
Perhaps someone here has seen this kind of error before and can point me in the right direction?

### Your System configuration
- Python version: 3.9.1
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: ffmpeg 4.3.1

### Is there an audio file you can include to help us reproduce?
The zipped archive of all the audio files is too large to attach to a GitHub issue, so I uploaded it and shared it via Google Drive: https://drive.google.com/file/d/12KJWKTnwJZ03EKTQrArlrUztoHv-1s8h/view?usp=sharing

Let me know if you have any issues accessing it.

**Comment by nbaddorf** [comment]
I am having the same issue
