### ISSUE TITLE
Issues in json decoding and ffmpeg options, fixes supplied :)

### ISSUE THREAD

**Issue by bababooey1234** [jiaaro/pydub#604]
Had two issues, but I was bored so I just opened the IDLE debugger and solved it myself lol.

### Fix #&#8203;1:

In utils.py, the lines:
```
info = json.loads(output)

if not info:
    # If ffprobe didn't give any information, just return it
    # (for example, because the file doesn't exist)
    return info
```
at line number 279 should be changed to:
```
try:
    info = json.loads(output)
except  json.decoder.JSONDecodeError:
    # If ffprobe didn't give any information, just return it
    # (for example, because the file doesn't exist)
    return info
```
This is because when json.loads is given an empty string as input it throws an error, and doesn't just return a falsy value.

### Fix #&#8203;2:
In audio_segment.py, the lines:
```
if cls.converter == 'ffmpeg':
    conversion_command += ["-read_ahead_limit", str(read_ahead_limit),
        "-i", "cache:pipe:0"]
```
at line 717 should be changed to:
```
if cls.converter == 'ffmpeg':
    conversion_command += ["-i", "cache:pipe:0"]
```
This is because this version of ffmpeg no longer supports the read_ahead_limit option, instead giving this error:
```
Unrecognized option 'read_ahead_limit'.
Error splitting the argument list: Option not found
```
### Your System configuration
- Python version: 3.8.3
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 2021-01-05-git-66deab3a26-full_build-www.gyan.dev
- OS: Windows

**Comment by xiaofeijiGH** [comment]
Hi,I was just experiencing JSONDecodeError. As you said,modify utils.py, but not work.
more details:

### Steps to reproduce
call function
AudioSegment.from_wav('void2.wav')

### Expected behavior
no exception

### Actual behavior
Traceback (most recent call last):
  File "G:/untitled/aa.py", line 6, in <module>
    AudioSegment.from_wav('void2.wav')
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\audio_segment.py", line 811, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\audio_segment.py", line 731, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\utils.py", line 280, in mediainfo_json
    info = json.loads(output)
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1


### Your System configuration
- Python version: 3.6.2
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version:  4.4-full_build-www.gyan.dev
- OS:Windows
### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by bababooey1234** [comment]
It doesn't look to me like you did modify utils.py, because if you did, the JSONDecodeError would be caught by the try/except around the `info=json.loads(output)` line.

Maybe try checking that the indentation around the area is correct, make sure that utils.py is saved before you run your program, and upload that section of utils.py so you can be sure you modified the right section in the right way.

**Comment by xiaofeijiGH** [comment]
Strangely, I just succeeded in using this method. Including audiosegment. From_ Mp3 () method is OK. I used to solve the problem of audiosegment. From_ Mp3 () failed to import the file successfully. Looking up the relevant information, it was found that it was the direct internal interface problem between pydub and ffmpeg.
Then I tried to update the version, but all the operations did not work on pycharm, but when I started today, I found that I could use the function successfully.
I infer that the problem may be in pycharm, but I don't have a specific clue.

**Comment by dfloer** [comment]
Also hitting the same JSONecodeError and ffmpeg issues.

@bababooey1234's first fix doesn't quite work, because `info` isn't defined in the return statement. Here's what worked for me:
```python
try:
    info = json.loads(output)
except  json.decoder.JSONDecodeError:
    # If ffprobe didn't give any information, just return it
    # (for example, because the file doesn't exist)
    return None
```

For the second, the fix worked on ffmpeg `4.4.4`.
