### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xiaofeijiGH** [jiaaro/pydub#605]
Steps to reproduce

call function
AudioSegment.from_wav('void2.wav')
Expected behavior

no exception
Actual behavior

Traceback (most recent call last):
File "G:/untitled/aa.py", line 6, in
AudioSegment.from_wav('void2.wav')
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\audio_segment.py", line 811, in from_wav
return cls.from_file(file, 'wav', parameters=parameters)
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\audio_segment.py", line 731, in from_file
info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\site-packages\pydub\utils.py", line 280, in mediainfo_json
info = json.loads(output)
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json_init_.py", line 354, in loads
return _default_decoder.decode(s)
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\xiaofeiji\Anaconda3\envs\pytorch\lib\json\decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
Your System configuration

    Python version: 3.6.2
    Pydub version: 0.25.1
    ffmpeg or avlib?: ffmpeg
    ffmpeg/avlib version: 4.4-full_build-www.gyan.dev
    OS:Windows

Is there an audio file you can include to help us reproduce?

You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by xiaofeijiGH** [comment]
I have solved it., but don't have idea. Maybe pycharm was the major problem... Try to restart your computer.

**Comment by wugoukanle** [comment]
i solve this problem by processing .wav file instead of .mp3
