### ISSUE TITLE
MemoryError with effect compress_dynamic_range

### ISSUE THREAD

**Issue by comes04** [jiaaro/pydub#607]
### Expected behavior
Hi, I try this to compress an audio file (.wav) with a duration of 9 minutes and 46 mb

```python
from pydub import AudioSegment
from pydub import effects

st = time.time()
sound = AudioSegment.from_file("prueba_normalizada.wav", "wav")
compressed_sound = effects.compress_dynamic_range(sound, -20.0, 2.0, 5.0, 40.0)
compressed_sound.export("prueba_comprimida_3.wav", format="wav")
```

### Actual behavior

After a while, i receive this error:

Traceback (most recent call last):
  File "C:/Users/moti/PycharmProjects/GUItutorial/venv/compress_pydub.py", line 10, in <module>
    compressed_sound = effects.compress_dynamic_range(sound)
  File "C:\Users\moti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydub\effects.py", line 187, in compress_dynamic_range
    return seg._spawn(data=b''.join(output))
MemoryError

I tryed with a little recording of about 5 seconds and did work properly.

Could be an issue due to the files weight?

Thanks in advance

### Your System configuration
- Python version: 3.6
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by comes04** [comment]
Moreover this, I tried a 7 minutes audio without issues, but with a 8 minutes one I get the same MemoryError.

Hope someone can help me.

**Comment by wykeenjenga** [comment]
I have encountered the same error when the audio file is above 8 min. @comes04  did you find any solution?
