### ISSUE TITLE
IndexError: list index out of range when merge mp3 files into one

### ISSUE THREAD

**Issue by wanghaisheng** [jiaaro/pydub#612]
```
combin sound to audio file
audiooutputdir directory exists D:\Download\audio-visual\auto_video-jigsaw\raw\reddit-popular\hzkbop\audio
audio mp3 found D:\Download\audio-visual\auto_video-jigsaw\raw\reddit-popular\hzkbop\audio\hzkbop.mp3
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 285, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__     
    return self.func(*args)
  File "auto_video.py", line 1860, in pure_generate
    process_thread_reddit(reddit_post_file) 
  File "auto_video.py", line 1897, in process_thread_reddit
    fastlane_generate(logfile)
  File "auto_video.py", line 1778, in fastlane_generate
    audio_add_whole(outputdir, filename, outputmp4withoutsound, outputmp4)
  File "auto_video.py", line 1512, in audio_add_whole
    audio = AudioFileClip(audio_file)       
  File "D:\Program Files\anaconda3\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "D:\Program Files\anaconda3\lib\site-packages\moviepy\audio\io\readers.py", line 
51, in __init__
    infos = ffmpeg_parse_infos(filename)    
  File "D:\Program Files\anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"
OSError: MoviePy error: failed to read the duration of file D:\Download\audio-visual\auto_video-jigsaw\raw\reddit-popular\hzkbop\audio\hzkbop.mp3.
Here are the file infos returned by ffmpeg: 

ffmpeg version 2021-07-21-git-f614390ecc-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy 
--enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb 
--enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57.  1.100 / 57.  1.100
  libavcodec     59.  3.102 / 59.  3.102
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[mp3 @ 00000149a1e5f240] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 00000149a1e5f240] Failed to read frame size: Could not seek to 1026.
D:\Download\audio-visual\auto_video-jigsaw\raw\reddit-popular\hzkbop\audio\hzkbop.mp3: Invalid argument
```
I have a bunch of mp3 files, when try to merge them into a whole new one.
```
        playlist_songs = glob.glob(outputdir+os.sep+"sound/*.mp3")
        combined = AudioSegment.empty()


        # let's just include the first 30 seconds of the first song (slicing
        # is done by milliseconds)
        for song in playlist_songs:
            parts = AudioSegment.from_mp3(song)
            combined = combined+parts

        # lets save it!
        with open(audio_file, 'wb') as out_f:
            combined.export(out_f, format='mp3')
```

another try
```
        merged = AudioSegment.empty()
        fConcat = list()
        for f in playlist_songs:
            name = AudioSegment.from_mp3(f)
            fConcat.extend([name])

        for f in fConcat:
            merged += f

        merged.export(audio_file, format="mp3")
```

just put a mp3 to test  also failed
[0.zip](https://github.com/jiaaro/pydub/files/7098350/0.zip)

**Comment by wanghaisheng** [comment]
if anyone here face the same issue,
if you want to merge mp3 files into a whole new one, here is the solution you should try ,specify codec
codec mp3 is not working.you can test that

```


        merged = AudioSegment.empty()
        fConcat = list()
        for f in playlist_songs:
            name = AudioSegment.from_file(f,format='mp3')
            fConcat.extend([name])

        for f in fConcat:
            merged += f


        print(len(merged))
        print(merged.dBFS)
        # setup  logging
        l = logging.getLogger("pydub.converter")
        l.setLevel(logging.DEBUG)
        l.addHandler(logging.StreamHandler())
        merged.export(audio_file, format="mp3", codec='libmp3lame')
```
