### ISSUE TITLE
Unknown input format: 'wma'

### ISSUE THREAD

**Issue by Djentmat** [jiaaro/pydub#625]
### Steps to reproduce

```
from pydub import AudioSegment

wav_audio = AudioSegment.from_file("disk1_1.wma", format="wma")
wav_audio.export("audio1.mp3", format="mp3")
```

### Expected behavior
Converting wma to mp3

### Actual behavior
```
Traceback (most recent call last):
  File "D:/_music/disk1/convert.py", line 3, in <module>
    wav_audio = AudioSegment.from_file("disk1_1.wma", format="wma")
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version N-104629-g18f22bfb27-20211121 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20210610
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libglslang --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20211121
  libavutil      57.  9.100 / 57.  9.100
  libavcodec     59. 13.100 / 59. 13.100
  libavformat    59.  9.101 / 59.  9.101
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 17.100 /  8. 17.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Unknown input format: 'wma'
```

### Your System configuration
- Python version: 3.8.7.0
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: ffmpeg version N-104629-g18f22bfb27-20211121

### Is there an audio file you can include to help us reproduce?
[disk1_1.zip](https://github.com/jiaaro/pydub/files/7576958/disk1_1.zip)

**Comment by Xalares** [comment]
Hi, just to say that I've got the same issue. Except with python 3.10.10

**Comment by tpcgold** [comment]
have the same issue but the strange thing: if you don't provide the format it just works with wma 🤷
