### ISSUE TITLE
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 53

### ISSUE THREAD

**Issue by michen00** [jiaaro/pydub#639]
I originally developed this app in Windows and was redeveloping it in Windows Subsystem for Linux. This line only gave me trouble in WSL even though the key versions are the same.

```
Traceback (most recent call last):
  File "/home/fizix/micromamba/envs/capstone_wsl_mm_38/lib/python3.8/site-packages/streamlit/script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "/home/fizix/MSVC/msvc/src/app.py", line 161, in <module>
    main()
  File "/home/fizix/MSVC/msvc/src/app.py", line 102, in main
    sample.export(format="wav", codec="pcm_s16le", bitrate="128k").read()
  File "/home/fizix/micromamba/envs/capstone_wsl_mm_38/lib/python3.8/site-packages/pydub/audio_segment.py", line 970, in export
    raise CouldntEncodeError(
pydub.exceptions.CouldntEncodeError: Encoding failed. ffmpeg/avlib returned error code: 53

Command:['ffmpeg.exe', '-y', '-f', 'wav', '-i', '/tmp/tmp6qgpy9ng', '-acodec', 'pcm_s16le', '-b:a', '128k', '-f', 'wav', '/tmp/tmpvuov3x5n']
```

Unfortunately, I don't have audio readily available to reproduce since the audio was recorded from the browser/device microphone.

How do I resolve this? Please advise.

### Your System configuration
- Python version: 3.8.12
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 4.2.2

**Comment by michen00** [comment]
I figured it out. In my case, I was missing PyAV. I ran this in terminal and my app ran end to end:
```micromamba install av -c conda-forge -y```
