### ISSUE TITLE
File Permission Error [Errno 13] when trying to play a song

### ISSUE THREAD

**Issue by Japhei** [jiaaro/pydub#641]
### Steps to reproduce
Use this default code:
```
from pydub import AudioSegment
from pydub.playback import play

song = AudioSegment.from_wav("cache/MySong.wav")
play(song)
```
### Console
```
(venv) C:\Python>python player.py
Traceback (most recent call last):
  File "C:\Python\player.py", line 53, in <module>
    play(song)
  File "C:\Python\venv\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "C:\Python\venv\lib\site-packages\pydub\playback.py", line 15, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\Python\venv\lib\site-packages\pydub\audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\Python\venv\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile       
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Japhei\\AppData\\Local\\Temp\\tmpqkm3c8oy.wav'
```

### Expected behavior
The program should play the song.

### Actual behavior
I guess the program copies the file to a temporary file to play it, but fails.

### Your System configuration
- Python version: 3.10.2
- Pydub version:  0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: latest

### Audiofile
any

**Comment by marcellonepitone** [comment]
I am having the same problem and cannnot seem to solve it. I tried running Python as administrator but that didn't change the result.

**Comment by CyberFoxar** [comment]
Issue is that `_play_with_ffplay` tries to use a `NamedTemporaryFile` for playback, which does not seem to work and is platform dependant, as per [the python doc](https://docs.python.org/3.9/library/tempfile.html#tempfile.NamedTemporaryFile). 

>  Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; **it cannot on Windows**)

Installing [simpleaudio](https://simpleaudio.readthedocs.io/en/latest/), as advised in the doc solves the issue on the user end, but simply hides the problem.
