### ISSUE TITLE
pydub.playback.play(),‘PermissionError: [Errno 13] Permission denied’

### ISSUE THREAD

**Issue by RickyWang111** [jiaaro/pydub#690]
### Steps to reproduce
```
from pydub.playback import play
from pydub import AudioSegment
a=AudioSegment.from_wav(r'G:\aaaa11.wav')
play(a)
```
### Expected behavior
Audio should be played normally.

### Actual behavior
Outputs of section "Steps to reporduce" mentioned:
```
G:\pythonProject\djangoProject\gongju_heji\Scripts\python.exe G:/gongju_heji/linshi/a_1.py 
Traceback (most recent call last):
  File "G:\gongju_heji\linshi\a_1.py", line 4, in <module>
    play(a)
  File "G:\pythonProject\djangoProject\gongju_heji\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "G:\pythonProject\djangoProject\gongju_heji\lib\site-packages\pydub\playback.py", line 15, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "G:\pythonProject\djangoProject\gongju_heji\lib\site-packages\pydub\audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "G:\pythonProject\djangoProject\gongju_heji\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Hasee\\AppData\\Local\\Temp\\tmppzzfa4vs.wav'
```

### Your System configuration
- Python version: 3.10.8
- Pydub version: 0.25.1
- ffmpeg or avlib?: ffmpeg
- ffmpeg/avlib version: 

### Is there an audio file you can include to help us reproduce?
You can include the audio file in this issue - just put it in a zip file and drag/drop the zip file into the github issue.

**Comment by hurdurderp** [comment]
Hello,
had the same issue. Use / instead of \ in the filepath
Like that:
`from pydub.playback import play
from pydub import AudioSegment
a=AudioSegment.from_wav(r'G:/aaaa11.wav')
play(a)`

**Comment by fleabiter** [comment]
The issue isn't opening the source sound file.  The issue is with pydub.playback.play() writing a file in the user's TEMP directory as shown in the last line of the @RickyWang111 output.  Perhaps somewhere in the utils.py code there is some code that Windows is choking on.  Someone suggested installing simpleaudio to replace the tempfile code but that didn't work for me.

I'm having the same problem on Windows 10 with Python 3.11.1 (released today)

I note that I have no trouble writing temporary files using the tempfile package.

**Comment by mian3kth** [comment]
I got the same problem and by luck I tested to set "delete=False" in the below code:
![python](https://user-images.githubusercontent.com/43177454/209802974-afea4fc0-7568-49da-a3bd-c864b6f91158.jpg)

**Comment by mian3kth** [comment]
This was after I installed ffmpeg and added it to path...
Now it plays the sound in my sample wav-file.
However, now it will fill up with a new wav file in temp directory each time I play the sound I guess... This problem is beyond my paygrade :-)

**Comment by fleabiter** [comment]
The errant code is likely in the utils.py where the code tries to figure out how near the temporary file is to being open.  The problem is shown as being in the function def _fd_or_path_or_tempfile where it tries to determine at what stage the opening of the temporary file is:  None, a string (the file path) or a file handle.

Ideally, the Tempfile wouldn't need to be checked and rechecked and I suspect the problem lies in trying to open a file that is already opened by either the TemporaryFile or NamedTemporaryFile functions of the tempfile package.

**Comment by kaiwangyu** [comment]
> I got the same problem and by luck I tested to set "delete=False" in the below code: ![python](https://user-images.githubusercontent.com/43177454/209802974-afea4fc0-7568-49da-a3bd-c864b6f91158.jpg)

thanks, it works for me

**Comment by ralrdsxo94** [comment]
mian3kth 님 감사합니다.

**Comment by maaz25925** [comment]
> I got the same problem and by luck I tested to set "delete=False" in the below code: ![python](https://user-images.githubusercontent.com/43177454/209802974-afea4fc0-7568-49da-a3bd-c864b6f91158.jpg)

It does indeed work but EVERY time you play an audio, it generates a temporary file which does NOT get deleted since you have provided that argument causing the memory to be filled with temporary files if you ever integrate this in an actual software.

**Comment by TiranoZero** [comment]
(Translate)
Mesmo fazendo isso aí, agora to recebendo esse erro:

![Captura de tela 2024-03-15 110256](https://github.com/jiaaro/pydub/assets/147494303/8a7a88df-d39e-4134-bbae-da3caed27903)

Failed to set value 'C:\Users\WINDOW~1\AppData\Local\Temp\tmp2kxg6ejz.wav' for 
option 'hide_banner': Option not found

**Comment by Sudheer-Nanduri** [comment]
For windows, installing [PyAudio](https://pypi.org/project/PyAudio/) solved the issue of permissions.

**Comment by freemedom** [comment]
i have to say that after i solved by "delete=False", ffplay still doesn't have sound in windows. so i used the pyaudio to play sound.

**Comment by deepkorat** [comment]
> For windows, installing [PyAudio](https://pypi.org/project/PyAudio/) solved the issue of permissions.

Installing the "PyAudio" library works well.
