### ISSUE TITLE
`AudioSegment.from_file` raises invalid exception

### ISSUE THREAD

**Issue by moonsikpark** [jiaaro/pydub#716]
### Steps to reproduce

With any image, for example with this image [https://dummyimage.com/300](https://dummyimage.com/300)

```
➜  ~ python3.11
Python 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydub
>>> pydub.AudioSegment.from_file("/Users/moonsikpark/Desktop/300.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/pydub/audio_segment.py", line 734, in from_file
    audio_codec = audio_streams[0].get('codec_name')
                  ~~~~~~~~~~~~~^^^
IndexError: list index out of range
>>>
```

### Expected behavior
`pydub.exceptions.CouldntDecodeError` should be raised because the file does not contain an audio stream.

### Actual behavior
`IndexError` is raised.

### Your System configuration
- Python version: `3.11.1`
- Pydub version: `0.25.1`
- ffmpeg or avlib?: `ffmpeg`
- ffmpeg/avlib version: `5.1.2`

### Comment

https://github.com/jiaaro/pydub/blob/996cec42e9621701edb83354232b2c0ca0121560/pydub/audio_segment.py#L730-L734

This seems to be an issue because of line 734, where it does not take into account that there could be a file that could be read with ffmpeg but has no audio stream.

I will prepare a simple PR that would resolve this.

**Comment by moonsikpark** [comment]
I have prepared #717 that will solves this. Please review.
