### ISSUE TITLE
audioop deprecation - Python 3.12

### ISSUE THREAD

**Issue by elderlabs** [jiaaro/pydub#725]
Audioop is deprecated as of Python 3.11, removal in 3.13 ([source](https://docs.python.org/3/library/audioop.html)). What's the plan for its replacement once it's no longer available? I've seen snippets floating around of audio manipulation with numpy arrays, but from my reading, it's also possible to overflow in instances of volume scaling/manipulation. It doesn't seem like there's an ideal solution to this or a replacement for audioop once it's gone. Perhaps someone will port it to a package...

Thanks.

**Comment by Tenzer** [comment]
pydub includes a pure-Python fallback for audioop. It is imported here:
https://github.com/jiaaro/pydub/blob/996cec42e9621701edb83354232b2c0ca0121560/pydub/utils.py#L14-L17

The implementation is here: https://github.com/jiaaro/pydub/blob/master/pydub/pyaudioop.py.

**Comment by aerilox** [comment]
pyaudioop is not an alternative. It does not provide a number of functions, like lin2alaw.
We have to stop upgrading python for existing and new audio code from 3.13. This is bad.

**Comment by jiaaro** [comment]
@aerilox I wrote pyaudioop to support basic features in pypy, and also contributed it to pypy. It was the original `audioop` implementation in pypy and the pypy folks developed it further. At that time pypy was an implementation of python 2.7. However [pypy still supports audioop in its py3.10 release](https://foss.heptapod.net/pypy/pypy/-/blob/branch/py3.10/lib_pypy/audioop.py), which could be a good starting point for an update to pyaudioop here. I'm not sure what the licensing implications would be there, though. pypy appears to be MIT licensed (same as pydub), so I think it'd be possible without too much trouble

**Comment by AraHaan** [comment]
Why not jus take the source code from the https://github.com/python/cpython/blob/3.12/Modules/audioop.c file and just put in with a ``setup.py`` that then is able to build it as a wheel and push it to pypi so then users could install it, then auto-builds it as a c extension module, and everyone be happy as then they can still use the module in newer python versions?

And then watch as it gets HUNDREDS OF MILLIONS OF DOWNLOADS and it makes the python core devs facepalm.

And for the ``setup.py`` this works:

```py
from setuptools import Extension, setup

# run: py -m pip install -e .

setup(
    name="audioop",
    version='3.12.4',
    # Describes how to build the actual extension module from C source files.
    ext_modules=[
        Extension(
            'audioop',
            ["audioop.c"],
            ['.'])]
)
```

**Comment by elderlabs** [comment]
That _would_ be the logical answer, yes. It's one that I considered, but as I'm not overly familiar with C type extensions, among other things required to make this happen, it was something I'd assumed someone else would pick up, preferably the original author of `audioop`, as it's their original work, and I wouldn't be much of one to maintain it in the slightest.

TL;DR it's a skill issue.

I'd be happy to experiment with making this happen so long as the original maintainer of it has no issue, though again, _I'm far from the right person to maintain such a thing long-term, especially in the case of memory allocations/leaks, vulnerabilities, and functionality should something change upstream._

Regards.

**Comment by AstralScribe** [comment]
You can try my package https://github.com/AstralScribe/python-audio

**Comment by AstralScribe** [comment]
I have created a package to replace audioop, you can try that, three functions are currently missing. 

https://github.com/AstralScribe/python-audio

**Comment by AlphastT101** [comment]
pip install audioop-lts
Works with python 3.13

**Comment by mcsantiago** [comment]
> pip install audioop-lts Works with python 3.13

Bless you for this!

**Comment by uche-exe** [comment]
> pip install audioop-lts Works with python 3.13

You, my friend, are an absolute legend!!

**Comment by yanhengxu98** [comment]
> pip install audioop-lts Works with python 3.13

You saved my live!

**Comment by McDic** [comment]
```
Python 3.13.2 (main, Mar 20 2025, 14:08:50) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydub import AudioSegment
Traceback (most recent call last):
  File "(omitted)/python3.13/site-packages/pydub/utils.py", line 14, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from pydub import AudioSegment
  File "(omitted)/python3.13/site-packages/pydub/__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "(omitted)/python3.13/site-packages/pydub/audio_segment.py", line 11, in <module>
    from .utils import mediainfo_json, fsdecode
  File "(omitted)/python3.13/site-packages/pydub/utils.py", line 16, in <module>
    import pyaudioop as audioop
ModuleNotFoundError: No module named 'pyaudioop'
```

Perhaps the root of 3rd party modules are not in `PYTHONPATH`. When I fixed that line to `from . import pyaudioop as audioop` then it worked.

**Comment by mcgrof** [comment]
So I think this should have better penv fallbacks:

try:                        
    import audioop
except ImportError:
    try:
        import pyaudioop as audioop
    except ImportError:
        from . import pyaudioop as audioop

**Comment by Danipulok** [comment]
> So I think this should have better penv fallbacks:
> 
> try: import audioop except ImportError: try: import pyaudioop as audioop except ImportError: from . import pyaudioop as audioop

Hey here, I have just encountered the same problem.

> ```python
> import pyaudioop as audioop
> ```

When does this part work?
It doesn't work when `pip install pydub` or similar is used

**Comment by Danipulok** [comment]
@mcgrof 

> So I think this should have better penv fallbacks:
> 
> try: import audioop except ImportError: try: import pyaudioop as audioop except ImportError: from . import pyaudioop as audioop

Hey here, I have just encountered the same problem.

> ```python
> import pyaudioop as audioop
> ```

When does this part work?
It doesn't work when `pip install pydub` or similar is used

**Comment by chemelli74** [comment]
What about adding

```
 install_requires=[
          'audioop-lts',
      ],
```

to setup.py ?

**Comment by jordancurve** [comment]
> pip install audioop-lts Works with python 3.13

The hero we need

**Comment by keithadler** [comment]
Fixed in #883: pydub now uses the `audioop-lts` wheel on Python 3.13+ and ships a rewritten pure-Python `pyaudioop` fallback (the old one was Python 2 code, which is why `pyaudioop` could never be imported). Until that lands, an installable build with the fix is at https://github.com/keithadler/pydub/releases/tag/v0.26.0:

```
pip install "pydub @ git+https://github.com/keithadler/pydub.git@v0.26.0"
```

Tested on 3.9-3.14 across Linux, macOS and Windows in CI.
