### ISSUE TITLE
FileNotFoundError while running the pydub module, was not happening before

### ISSUE THREAD

**Issue by fau1095** [jiaaro/pydub#749]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Your System configuration
- Python version: 3.11
- Pydub version: pydub-0.25.1
- ffmpeg or avlib?: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning
- ffmpeg/avlib version: 

`#Coded by Fau, all rights reserved

from pytube import YouTube
from pydub import AudioSegment
from sys import argv
from pathlib import Path
import os
import shutil
from dotenv import load_dotenv
load_dotenv()

link = input((argv[0]) + "\n Enter the URL: ")

yt = YouTube(link)

myDesiredFolder = os.environ.get('DESIRED_FOLDER_PATH')

print("Title: ", yt.title)
print("Views: ", yt.views)

ya = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()

ya.download()

def downloadedFile():
# Convert mp4 to mp3
    file_name = yt.title + '.mp4'
# Specify the complete file path for the input MP4 file
    input_file_path = os.path.join(os.getcwd(),file_name)
    sound = AudioSegment.from_file(file_name, format="mp4")

# Set the mp3 file name
# Specify the complete file path for the output MP3 file
    #mp3_file = yt.title + '.mp3'
    mp3_file = os.path.join(os.getcwd(), yt.title + '.mp3')
# Export the mp3 file
    try:    
        sound.export(mp3_file, format="mp3")
    except Exception as e:
        print("Error during MP4 to MP3 conversion:",e)    

# Delete the mp4 file
    #os.remove(file_name)
    os.remove(input_file_path)

# Create the destination folder if it doesn't exist    
    folder_location = myDesiredFolder
    if not os.path.exists(folder_location):
        os.makedirs(folder_location)
# Move the MP3 file to the destination folder
    shutil.move(mp3_file, folder_location)

downloadedFile()`

I get the following error:

Traceback (most recent call last):
  File "/Users/fabriziomendez/Documents/Automations/YTDownloader/ytDownloader.py", line 75, in <module>
    downloadedFile()
  File "/Users/fabriziomendez/Documents/Automations/YTDownloader/ytDownloader.py", line 52, in downloadedFile
    sound = AudioSegment.from_file(file_name, format="mp4")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydub/audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Smooth Guitar Beat - "Moody" (Prod. Pacific).mp4'

**Comment by fau1095** [comment]
This wasn't happening a few days back, nothing was changed in my code, therefore I suspect the issue is related to the pydub library

**Comment by fau1095** [comment]
This wasn't happening a few days back, nothing was changed in my code, therefore I suspect the issue is related to the pydub library

**Comment by mabdelfattah** [comment]
This is happening randomly to me for the past few weeks!

**Comment by josebruzzoni** [comment]
Hi, any solution on this? this is happening to me too

**Comment by AInisha** [comment]
does anybody have the solution?
