### ISSUE TITLE
test failures on python 3.12

### ISSUE THREAD

**Issue by xiota** [jiaaro/pydub#790]
```
/home/main-builder/pkgwork/src/pydub-0.25.1/test/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\('
  m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)
/home/main-builder/pkgwork/src/pydub-0.25.1/test/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\('
  m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)
/home/main-builder/pkgwork/src/pydub-0.25.1/test/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(flt)p?( \(default\))?$', token):
/home/main-builder/pkgwork/src/pydub-0.25.1/test/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(dbl)p?( \(default\))?$', token):
........................................E....................................................................E...
======================================================================
ERROR: test_from_file_clean_fail (__main__.AudioSegmentTests.test_from_file_clean_fail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main-builder/pkgwork/src/pydub-0.25.1/test/test.py", line 1089, in test_from_file_clean_fail
    self.assertEquals(files, [os.path.basename(tmp_wav_file.name)])
    ^^^^^^^^^^^^^^^^^
AttributeError: 'AudioSegmentTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

======================================================================
ERROR: test_split_on_silence_complete_silence (__main__.SilenceTests.test_split_on_silence_complete_silence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main-builder/pkgwork/src/pydub-0.25.1/test/test.py", line 1112, in test_split_on_silence_complete_silence
    self.assertEquals( split_on_silence(seg), [] )
    ^^^^^^^^^^^^^^^^^
AttributeError: 'SilenceTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

----------------------------------------------------------------------
Ran 113 tests in 12.501s
```

**Comment by unitof** [comment]
This was fixed in https://github.com/jiaaro/pydub/commit/5658398518f84a7669ba75b8abbb368ce48e145d but doesn't seem to have made it to a release.

**Comment by xiota** [comment]
I see a large number of pull requests and issues... is there a fork that addresses the major problems?
